### ISSUE TITLE
Tech Tree - Tantros capacitor in Erekir tech tree

### ISSUE THREAD

**Issue by YourLocalRepoMan** [Twcash/Tantros-Test#35]
**Bug Description**
When playing the Mindustry campaign with the Aquarion mod (installed through the mod) browser built into Mindustry, the capacitor structure (added by this mod) is in the Erekir tech tree, and requires Tantros items (sodium, lead, bauxite, and metaglass) to unlock.

**To Reproduce**
1. Remove all mods except for the version of Aquarion in the in-game mod browser, or start with a fresh mindustry installation, then click mods, mod browser, aquarion, 
2. Click play, then campaign.
3. Unlock both tech trees far enough by finishing the first level of Erekir and producing Sodium in Tantros. (this can be skipped if you have already played far enough in both campaigns to unlock those technologies)
4. Click "tech tree"
5. Click "Erekir"
6. Capacitor technology is located above and to the left of "beam node"

**Expected behavior**
Expected behavior is that all technologies requiring Tantros items are located within the Tantros tech tree.

**Screenshot**
![20240515_11h59m54s_grim](https://github.com/Twcash/Tantros-Test/assets/169915588/00a28414-ea49-42c9-8ff1-eebca66ef3cf)

**Software:**
 - OS: Fedora 39
 - Mindustry version: Release build 146, installed from flatpak
 - Mod version: neither the mod browser nor the mod files list the version of this mod

**Additional information**
There may be other items from this mod in other tech trees, as I have not played much of Serpulo, and I am still less than 1/4 of the way through the Erekir campaign. If there are technologies in more end-game locations in the Serpulo or Erekir tech trees, I would not have found them.

**Comment by Twcash** [comment]
thats on me fixed now
