### ISSUE TITLE
Put the item and liquid bridges and junctions

### ISSUE THREAD

**Issue by FrozenEdge** [Twcash/Tantros-Test#5]
I know, this is not a bug.

But take this as a recommendation, I play the mod and at some point it is very difficult to transport the elements to all parts of the map, because the bridges and junctions of elements and liquids do not exist. And the game has a limit to place cargo units.

**Comment by Twcash** [comment]
Hello. I understand how you may struggle with this. But many people who have played this have found solutions to these problems. Tantros is about optimization with you limited resources. Thankfully there will be a way to transport items short distances without the cargo drones. Also liquid bridges and junctions do exist.

**Comment by FrozenEdge** [comment]
Liquido bridges do exist in tantra but not the junctions

**Comment by Twcash** [comment]
... they do

**Comment by Twcash** [comment]
not implemented yet if thats what your asking

**Comment by Twcash** [comment]
There you go... added mass drivers
