### ISSUE TITLE
Basalt crags

### ISSUE THREAD

**Issue by Andromeda-Galaxy29** [Twcash/Tantros-Test#6]
I'm not sure, but I'm guessing those black squares aren't supposed to be there
![Screenshot_20240214_092856.jpg](https://github.com/Twcash/Tantros-Test/assets/137232272/06ba8d20-ff2f-4205-8ce2-5c89d014a4be)

**Comment by Twcash** [comment]
They aren’t meant to be liquids it’s empty tiles
